### ISSUE TITLE
Build new Issue relationships after creation

### ISSUE THREAD

**Issue by aiwilliams** [JupiterOne/jupiter-integration-jira#14]
The Issue is ingested immediately, but there are no relationships built.

**Comment by befirst** [comment]
I have added a test for checking creation of relationship and it is passed. @aiwilliams, can you please provide more information about that bug, so we can check it more accurately

**Comment by aiwilliams** [comment]
@befirst I've merged the additional tests, thank you. The assertions about the "new data" model are helpful.

I recently refactored code to support a simple array of project keys, since our UI can only provide a simple array of strings at this time. During that work, I observed that the `executionHandler` would fetch data from the graph during the `CREATE_ENTITY` operation, and run through `publishChanges` with all the loaded graph data, though the "new data" model would include only the new Jira Issue and relationships. I believe this would lead to producing operations to delete data in the graph which was not found in the "new data" model. Therefore, I changed the `executionHandler` code to only send the new Issue entity, and noted that relationships would not longer be delivered. There were no failing tests which demonstrated that delete operations were expected or not expected.

I think the solution is as simple as sending an empty `JupiterOneDataModel` into `publishChanges` when operating on `CREATE_ENTITY`, but to prove this works, there would need to be a change to the tests to ensure that the correct operations are produced.

**Comment by aiwilliams** [comment]
The changes I recently made to address the need to support a simple array of project keys, and also changed `executionHandler` to send only create operation for entity: https://github.com/JupiterOne/jupiter-integration-jira/commit/b6b4e8e7748bbb72e0f5b8eb339742acbf9b4fd0

**Comment by befirst** [comment]
Got it, I will take it soon
