### ISSUE TITLE
Add ability to create issue

### ISSUE THREAD

**Issue by artempartos** [JupiterOne/jupiter-integration-jira#4]

**Comment by aiwilliams** [comment]
It's looking more and more like this structure will be present at `executionContext.event.action`:

```json
{
  "name": "CREATE_ENTITY",
  "class": "Vulnerability",
  "properties": {
    "summary": "...",
    "description": "...",
    "classification": "...",
  }
}
```

The integration should create an Issue, mapping `properties` as appropriate from the incoming `Vulnerability` (for example) into the Issue, and then publish a `CREATE_ENTITY` operation to the persister which has the class `['Record', 'Vulnerability']` and appropriate data from Issue (which should be data from the action).

@erkangz, can you confirm, we want the additional class `Vulnerability` on these record entities, right?

**Comment by aiwilliams** [comment]
First pass at this created by 81b3934a5fe500427c62be13007a1029cc0e9d9a.
