### ISSUE TITLE
Ingest new Jira issue immediate after it is created

### ISSUE THREAD

**Issue by aiwilliams** [JupiterOne/jupiter-integration-jira#7]
An Issue can be created by a `CREATE_ENTITY` action. However, it is not ingested into the graph until the next `INGEST` run of the integration. The Issue should be ingested in the same execution cycle that handles creating the issue.

**Comment by Andrew8xx8** [comment]
This behavior should work. There is a test to cover it https://github.com/JupiterOne/jupiter-integration-jira/blob/master/src/persister/publishChanges.test.ts#L469
After creating an issue this code provides empty array as old data and array with the one created issue as a new data to `processEntities` method of persister.

**Comment by aiwilliams** [comment]
Ahh, I see. Thanks @Andrew8xx8.
